#+TITLE: NPTEL Demo
#+AUTHOR: Sai Gollapudi & Sadhana Reddy
#+DATE: May, 2017

* Introduction
We are looking to showcase how Renarration can be effectively applied to NPTEL
to increase its accessibility. In the process, we aim to also associate Virtual
Labs with this effort, as it too is yet another India MHRD effort for the
betterment of student education.


* Approach Used
Our approach is to develop the demo in increments. 
+ Demo V1.0: Apply multiple Renarration techniques to existing NPTEL pages and
  show how it meets a critical accessibility need for NPTEL.
  ++ Demo V1.0: Shows a static NPTEL page being modified by various Bookmarklet
  oriented renarration modifications.
  ++ Demo V1.1: Renders a static NPTEL page in a novel way. That is, present
  the original NPTEL source in an alternate view. This shows how a
  user institution can customize the generic page of NPTEL to their specific
  community purposes.
  ++ Demo V1.2: Augment the alternate rendering of a NPTEL page with
  information that is currently not present in source NPTEL page. This can be
  static information obtained from a file.
  ++ Demo V1.3: Augment the alternate rendering with configurable data 
  ++ Demo V1.4: Augment the alternate rendering with NPTEL page-extracted data
+ Demo V2.0: Make the Renarration more intelligent by utilizing a backend
  knowledge base which leverages NPTEL, Virtual Labs and GATE-syllabus.  
  ++ Demo V2.1: 


* Demo V1.0

* Demo V2.0
In this demo we are trying to make the renarration intelligent by associating
it with a backend Knowledge Base (KB). The KB will be based on a conceptual
representation of information that links and instanciates NPTEL, VLABs, and
GATE-Syllabus information. In our demo implementation, we aim to scope the work
down to simple representative samples only. 

